# Project information
site_name: Chaos Manager
site_author: Insurgentes Estelares
site_description: >-
  Documentação para do projeto Chaos Manager realizado na disciplina de
  Requisitos de Software na Universidade de Brasília

# Repository
repo_url: https://github.com/mdsreq-fga-unb/2023.2-ChaosManager
repo_name: Chaos Manager

# Configuration
docs_dir: docs
theme:
  hide_toc: true
  name: material
  language: pt-BR
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
  features:
    - navigation.instant
    - navigation.section
    - navigation.path
    - navigation.top
    - tabs

  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro
      primary: deep purple
      accent: purple
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
      primary: deep purple
      accent: purple

# Page tree
nav:
  - Início: index.md
  - Insurgentes Estelares: historia.md
  - Missão 1:
      - Visão geral do produto: visao_produto.md
      - Visão geral do projeto: visao_projeto.md
      - Processo de desenvolvimento: processo_software.md
      - Lições aprendidas: licoes1.md
      - Vídeo de apresentação: entregas1.md
  - Missão 2:
      - Verificação e validação - Crystaleum: verEval.md
      - Backlog SAFe: backlog.md
      - Priorização e MVP: priorizacaoMVPSafe.md
      - Lições aprendidas: licoes2.md
      - Vídeo de apresentação: entregas2.md
  - Missão 3:
      - Verificação e validação - MoonWalkers: verEvalMoonWalkers.md
      - PBB: pbb.md
      - BDD: bdd.md
      - USM: usm.md
      - Lições aprendidas: licoes3.md
      - Vídeo de apresentação: entregas3.md
  - Casos de uso: casodeUso.md
  - Iterações: 'iterações_total.md

# Extensions
markdown_extensions:
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
